config/routes.rb
Rails.application.routes.draw do

  
  match 'products/checkout', to: 'products#checkout', via: [:get, :post]
  match 'products/order', to: 'products#order', via: [:get, :post]
  resources :products

  root 'products#index'

end

app/models/order_session.rb
class OrderSession < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :name, :description, :price,  presence: true
	validates :price, :format => { :with => /\A\d+(?:\.\d{0,2})?\z/, :message => "should be either numeric or float upto two decimal places." }, :numericality => {:greater_than => 0, :less_than => 1000000}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def checkout
    respond_to do |format|
      if params["products_list"].nil? && session[:token].nil?
        format.html{redirect_to products_url}
      else
        if params["products_list"] == ""
          format.html{redirect_to products_url}
        elsif params["products_list"].present?
          session[:token] = generate_token
          OrderSession.create(products_list: params["products_list"], token: session[:token])
          @arr = params["products_list"].split(',')
          @order = Product.where(id: @arr.uniq)
        else
          order = OrderSession.find_by_token(session[:token])
          @arr = order.products_list.split(',')
          @order = Product.where(id: @arr.uniq)
        end
        format.html
      end
    end 
  end

  def order
    respond_to do |format|
      if rand(2..15).even?
        order = OrderSession.find_by_token(session[:token])
        @arr = order.products_list.split(',')
        @order = Product.where(id: @arr.uniq)
        transaction = {}
        transaction["id"] = "txn_1A6GLtK3DDW0KDALzgG5oPEc"
        transaction["amount"] = params["price"]
        @transaction = transaction
        reset_session
        format.html
      else
        format.html { redirect_to products_checkout_path, notice: 'Payment is failed please try after some time.' }
      end
    end
  end

  private
    #Generate token to save cart data
    def generate_token
      o = [('a'..'z'), ('A'..'Z')].map(&:to_a).flatten
      token = (0...50).map { o[rand(o.length)] }.join
      return token
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper

	def get_piece(arr, id)
		arr.count{|x| x == id.to_s}
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GlProduct</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product, validate: true, :html => { :class => "form-horizontal product" } do |f| %>

  <% if @product.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-3">
      <%= f.text_field :name, :class => 'form-control', presence: true %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-3">
      <%= f.text_area :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>
  <div class="form-group">
    <%= f.label :price, :class => 'control-label col-lg-2' %>
    <div class="col-lg-3">
      <%= f.text_field :price, :class => 'form-control' %>
    </div>
    <%=f.error_span(:price) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-1 col-lg-3">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                products_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/products/_product.html.erb
<tr><td><%= link_to product.id, product_path(product) %></td>
<td><%= product.name %></td>
<td><%= product.description %></td>
<td><%= product.price %></td>
<td><%=l product.created_at %></td>
<td>
<%= button_tag t('.cart', :default => t("helpers.links.cart")),
            :onclick => "createCookie('product', #{product.id}, 1)", :class => 'btn btn-success btn-xs' %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
            edit_product_path(product), :class => 'btn btn-default btn-xs' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
            product_path(product),
            :method => :delete,
            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure you want to delete this product?')) },
            :class => 'btn btn-xs btn-danger' %>
</td></tr>

app/views/products/checkout.html.erb
<%- model_class = Product -%>
<% g_total = 0 %>
<% if flash[:notice] %>
<div class="alert alert-warning"><%= flash[:notice] %></div>
<% end %>
<div class="container">
<table class="table table-striped">
	<thead>
      <tr>
        <th width="15%"><%= model_class.human_attribute_name(:name) %></th>
        <th width="15%"><%= model_class.human_attribute_name(:price) %></th>
        <th width="15%">Pieces</th>
        <th width="20%">Total</th>
      </tr>
    </thead>
    <% @order.each do |order|%>
    <tr>
    	<td><%= order.name%></td>
    	<td><%= order.price%></td>
    	<td><%= pices = get_piece(@arr, order.id)%></td>
    	<td><% total = (pices*order.price) %><% g_total = g_total + total %><%= total %></td>
    </tr>
    <% end %>
    <tr><td colspan="3" align="right">Grand Total</td>
    	<td>
    	<%= form_tag products_order_path, method: :post  do %>
        <%= hidden_field_tag 'price', "#{g_total}"   %>
        <%= g_total %>&nbsp;&nbsp;<%= button_tag "Order Now", :class => "btn btn_success"%>
        <% end %>
        </td>
        </tr>
</table>
</div>

app/views/products/edit.html.erb
<div class="container">
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>
</div>

app/views/products/index.html.erb
<%= javascript_include_tag 'product'%>
<div class="container">
  <%- model_class = Product -%>
  <div class="page-header">
    <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  <%= link_to t('.new', :default => t("helpers.links.new")),new_product_path,:class => 'btn btn-primary' %>
  <div style="text-align: right;font-size: 20px;">Cart Items&nbsp;&nbsp;<strong id="items"></strong>&nbsp;&nbsp;
    <div style="float: right;">
      <%= form_tag products_checkout_path, method: :post  do %>
        <%= hidden_field_tag 'products_list'    %>
        <%= button_tag "Checkout", :class => "btn btn-success", :onclick => "goForCheckout()"%>
      <% end %>
    </div>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <th width="15%"><%= model_class.human_attribute_name(:id) %></th>
        <th width="15%"><%= model_class.human_attribute_name(:name) %></th>
        <th width="20%"><%= model_class.human_attribute_name(:description) %></th>
        <th width="15%"><%= model_class.human_attribute_name(:price) %></th>
        <th width="15%"><%= model_class.human_attribute_name(:created_at) %></th>
        <th width="20%"><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody id="products">
      <%= render partial: "product", collection: @products %>
    </tbody>
  </table>
  <div class="digg_pagination" style="float: left;padding: 10px;">
    <%= will_paginate @products, :container => false %>
  </div>
  <% unless @products.total_pages < 2 %>
    <%= link_to 'Load More', products_path(:page => params[:page].to_i == 0 ? 2 : params[:page].to_i+1), :remote => true, :id => 'show_more_link', :class => "btn btn-success" %>
  <% end %>
</div>

app/views/products/index.js.erb
$("#products").append("<%= escape_javascript render partial: 'product', collection: @products %>");

// Hide link if it is last page otherwise update link
<% if @products.total_pages == @products.current_page %>
    $("#show_more_link").hide();
<% else %>
    $("#show_more_link").attr("href", "<%= products_path(:page => (@products.current_page + 1)) %>");
<% end %>

app/views/products/new.html.erb
<div class="container">
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>
</div>

app/views/products/order.html.erb
<div class="container">
    <div class="page-header"><h3>Thanks</h3>
    </div>
    <div class="row">
        <div class="col-sm-6 col-md-6">
            <div class="alert alert-success">
                <%= link_to "Back to list", products_path, :class => "btn close" %>
               <span class="glyphicon glyphicon-ok"></span> <strong>Your order is successfully placed</strong>
                <hr class="message-inner-separator">
                <p style="float: left;"><strong>Products</strong></p><div style="float: right;"><strong>Details</strong></div><br/><br/>
                <% @order.each do |order|%>
                <p style="float: left;"><%= order.name%></p><div style="float: right;"><%= pices = get_piece(@arr, order.id)%></div><br/>
                <% end %>
                <p style="float: left;">Transaction Id</p><div style="float: right;"><%= @transaction["id"] %></div><br/><br/>
                <p style="float: left;">Amount</p><div style="float: right;"><%= @transaction["amount"] %></div><br/><br/>
            </div>
        </div>
        
        
    </div>
</div>

app/views/products/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @product.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @product.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @product.price %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              products_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_product_path(@product), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              product_path(@product),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>